sudo: required
services:
  - docker
script:
  - docker run --rm -v $PWD:/usr/src/app -w /usr/src/app -v go:/go golang:1.8 bash -c "go get -d -v -t && go test && go build"
branches:
  only:
    - master
